server:
  adminContextPath: /
  applicationContextPath: /
  applicationConnectors:
    - type: http
      port: 5000
  adminConnectors:
    - type: http
      port: 5001


slowServer:
  url: http://localhost:8080/slowService
  timeout: 2000

httpClient:
  maxConnections: 5
  maxConnectionsPerRoute: 5
  keepAlive: 30s
  retries: 0
  gzipEnabledForRequests: false